
# Channel names for ID lookup (used by helper script)
CHANNEL_NAMES = {
    "KR": [
        "김프로KIMPRO",
        "BLACKPINK",
        "HYBE LABELS",
        "CuRe 구래",
        "ToyPuddingTV",
        "1MILLION Dance Studio",
        "GH'S",
        "KBS WORLD TV",
        "ROSÉ",
        "유백합 kkubi99",
        "Jane ASMR 제인",
        "JFlaMusic",
        "Hongyu ASMR 홍유",
        "BIGBANG",
        "보겸TV",
        "핑크퐁 (인기 동요·동화)",
        "SEVENTEEN",
        "설기영SULGI",
        "BIBO와 장난감",
        "GONGSAM TABLE 이공삼",
        "Boram Tube ToysReview [보람튜브 토이리뷰]",
        "KKUBI STUDIO",
        "서은원숭이아기",
        "[햄지]Hamzy",
        "TOMORROW X TOGETHER OFFICIAL",
        "Byungari 병아리언니",
        "ENHYPEN",
        "유창조 You Chang Jo",
        "Foodie Mama",
        "소영 Ssoyoung",
    ],
    "JP": [
        "PewDiePie",
        "ISSEI / いっせい",
        "Junya.じゅんや",
        "Sagawa / さがわ",
        "Saito",
        "Pokémon Kids TV",
        "Bayashi TV",
        "HAYATAKU はやたく",
        "BRUNO",
        "Parotter",
        "はじめしゃちょー（hajime）",
        "Cafe Music BGM channel",
        "Mazizien",
        "きまぐれクックKimagure Cook",
        "Mochi.もち",
        "M2 Family",
        "Nonomen ノノメン",
        "THE FIRST TAKE",
        "Alina & Amelia",
        "せんももあいしーチャンネル",
        "Yoshipapa / よしパパ",
        "恋愛とと",
        "すしらーめん《りく》",
        "Yamil4K",
        "ASMR FOOD",
        "Fischer's-フィッシャーズ-",
        "AKIRA♂",
        "mania japansong",
        "Ado",
        "Kenshi Yonezu 米津玄師",
    ],
    "US": [
        "MrBeast",
        "Cocomelon - Nursery Rhymes",
        "Vlad and Niki",
        "Kids Diana Show",
        "Stokes Twins",
        "Like Nastya",
        "Alan's Universe",
        "A4",
        "Baby Shark - Pinkfong Kids' Songs & Stories",
        "5-Minute Crafts",
        "Toys and Colors",
        "Topper Guild",
        "Mark Rober",
        "Movieclips",
        "Dude Perfect",
        "LooLoo Kids - Nursery Rhymes and Children's Songs",
        "Zhong",
        "Marshmello",
        "Billion Surprise Toys",
        "Billie Eilish",
        "Masha and The Bear",
        "MrBeast 2",
        "MrBeast Gaming",
        "Genevieve's Playhouse - Learning Videos for Kids",
        "Ben Azelart",
        "DaFuq!?Boom!",
        "Katy Perry",
        "IShowSpeed",
        "Vlad và Niki",
        "Like Nastya Show",
    ],
}

# Channel IDs - populated by running the helper script once
# This avoids using the expensive search API (100 units per search)
CHANNEL_IDS = {
    "KR": [
        # TODO: Run scripts/collect_channel_ids.py to populate these IDs
    ],
    "JP": [
        # TODO: Run scripts/collect_channel_ids.py to populate these IDs
    ],
    "US": [
        # TODO: Run scripts/collect_channel_ids.py to populate these IDs
    ],
}
